version: '3.9'
services:
  db:
    image: postgis/postgis:15-3.3
    container_name: postgis-db
    environment:
      POSTGRES_USER: usuario         # Novo usuário
      POSTGRES_PASSWORD: projeto     # Nova senha
      POSTGRES_DB: sistema-de-usuarios
    ports:
      - "5432:5432"
    volumes:
      - postgis-data:/var/lib/postgresql/data

volumes:
  postgis-data:
